### ISSUE TITLE
Gorp fails to compile with Go1.1

### ISSUE THREAD

**Issue by rickb777** [go-gorp/gorp#37]
Trying to build the current tip fails thusly:

./gorp.go:699: too many arguments in call to insert
./gorp.go:699: insert(m, m, list...) used as value
./gorp.go:713: too many arguments in call to update
./gorp.go:713: not enough arguments to return
./gorp.go:746: too many arguments in call to get
./gorp.go:746: not enough arguments to return
./gorp_test.go:783: insert redeclared in this block
    previous declaration at ./gorp.go:1339
./gorp_test.go:790: update redeclared in this block
    previous declaration at ./gorp.go:1290
./gorp_test.go:807: get redeclared in this block
    previous declaration at ./gorp.go:1188
./gorp_test.go:860: rawselect redeclared in this block
    previous declaration at ./gorp.go:1032
./gorp.go:746: too many errors
FAIL    gorp [build failed]
